### ISSUE TITLE
How to configure specific credentials just for SES?

### ISSUE THREAD

**Issue by davidwessman** [aws/aws-actionmailer-ses-ruby#5]
### Describe the issue

We have been using specific credentials for our SES vs our S3.
S3-config is handled via Shrine, but for SES we have used:

```ruby
credentials = Aws::Credentials.new(
  username,
  password
)
Aws::Rails.add_action_mailer_delivery_method(
  :ses,
  credentials: credentials,
  region: region
)
```

In the README it says:
> You will have to ensure that you provide credentials for the SDK to use. See the latest [AWS SDK for Ruby Docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html#Configuration) for details.

Is it possible to add it like:

```ruby
    config.action_mailer.delivery_method = :ses
    config.action_mailer.ses_settings = {
      ...      
    }
```

### Links

https://github.com/aws/aws-actionmailer-ses-ruby/blob/main/README.md

**Comment by mullermp** [comment]
Yes, when upgrading to aws-sdk-rails v5, and using 1.0.0 version of this gem, you should be able to pass credentials and other Client options into those ses_settings configuration hashes. Please reopen if there is an issue.
